version: '2'
services:
  redis:
    image: redis
    expose:
      - '6379'

  app:
    build: .
    env_file:
      - .env.default
    ports:
      - "3000"
    labels:
      - "SERVICE_3000_CHECK_TCP=true"
      - "SERVICE_3000_CHECK_INTERVAL=15s"
      - "SERVICE_3000_NAME=hangops-jobbot"
      - "SERVICE_3000_TAGS=load-balance,urlprefix-hangops-jobbot.*/"
    depends_on:
      - redis
